// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.0
// source: api/appeal/v1/appeal.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OpCreateAppealRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppealId int64  `protobuf:"varint,1,opt,name=appeal_id,json=appealId,proto3" json:"appeal_id,omitempty"`
	OpRemark string `protobuf:"bytes,2,opt,name=op_remark,json=opRemark,proto3" json:"op_remark,omitempty"`
	OpUser   string `protobuf:"bytes,3,opt,name=op_user,json=opUser,proto3" json:"op_user,omitempty"`
}

func (x *OpCreateAppealRequest) Reset() {
	*x = OpCreateAppealRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_appeal_v1_appeal_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpCreateAppealRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpCreateAppealRequest) ProtoMessage() {}

func (x *OpCreateAppealRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_appeal_v1_appeal_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpCreateAppealRequest.ProtoReflect.Descriptor instead.
func (*OpCreateAppealRequest) Descriptor() ([]byte, []int) {
	return file_api_appeal_v1_appeal_proto_rawDescGZIP(), []int{0}
}

func (x *OpCreateAppealRequest) GetAppealId() int64 {
	if x != nil {
		return x.AppealId
	}
	return 0
}

func (x *OpCreateAppealRequest) GetOpRemark() string {
	if x != nil {
		return x.OpRemark
	}
	return ""
}

func (x *OpCreateAppealRequest) GetOpUser() string {
	if x != nil {
		return x.OpUser
	}
	return ""
}

type OpCreateAppealReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OpCreateAppealReply) Reset() {
	*x = OpCreateAppealReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_appeal_v1_appeal_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpCreateAppealReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpCreateAppealReply) ProtoMessage() {}

func (x *OpCreateAppealReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_appeal_v1_appeal_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpCreateAppealReply.ProtoReflect.Descriptor instead.
func (*OpCreateAppealReply) Descriptor() ([]byte, []int) {
	return file_api_appeal_v1_appeal_proto_rawDescGZIP(), []int{1}
}

type UpdateAppealRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateAppealRequest) Reset() {
	*x = UpdateAppealRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_appeal_v1_appeal_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateAppealRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAppealRequest) ProtoMessage() {}

func (x *UpdateAppealRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_appeal_v1_appeal_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAppealRequest.ProtoReflect.Descriptor instead.
func (*UpdateAppealRequest) Descriptor() ([]byte, []int) {
	return file_api_appeal_v1_appeal_proto_rawDescGZIP(), []int{2}
}

type UpdateAppealReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateAppealReply) Reset() {
	*x = UpdateAppealReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_appeal_v1_appeal_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateAppealReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAppealReply) ProtoMessage() {}

func (x *UpdateAppealReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_appeal_v1_appeal_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAppealReply.ProtoReflect.Descriptor instead.
func (*UpdateAppealReply) Descriptor() ([]byte, []int) {
	return file_api_appeal_v1_appeal_proto_rawDescGZIP(), []int{3}
}

type DeleteAppealRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteAppealRequest) Reset() {
	*x = DeleteAppealRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_appeal_v1_appeal_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAppealRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAppealRequest) ProtoMessage() {}

func (x *DeleteAppealRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_appeal_v1_appeal_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAppealRequest.ProtoReflect.Descriptor instead.
func (*DeleteAppealRequest) Descriptor() ([]byte, []int) {
	return file_api_appeal_v1_appeal_proto_rawDescGZIP(), []int{4}
}

type DeleteAppealReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteAppealReply) Reset() {
	*x = DeleteAppealReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_appeal_v1_appeal_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAppealReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAppealReply) ProtoMessage() {}

func (x *DeleteAppealReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_appeal_v1_appeal_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAppealReply.ProtoReflect.Descriptor instead.
func (*DeleteAppealReply) Descriptor() ([]byte, []int) {
	return file_api_appeal_v1_appeal_proto_rawDescGZIP(), []int{5}
}

type GetAppealRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAppealRequest) Reset() {
	*x = GetAppealRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_appeal_v1_appeal_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAppealRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppealRequest) ProtoMessage() {}

func (x *GetAppealRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_appeal_v1_appeal_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppealRequest.ProtoReflect.Descriptor instead.
func (*GetAppealRequest) Descriptor() ([]byte, []int) {
	return file_api_appeal_v1_appeal_proto_rawDescGZIP(), []int{6}
}

type GetAppealReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAppealReply) Reset() {
	*x = GetAppealReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_appeal_v1_appeal_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAppealReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppealReply) ProtoMessage() {}

func (x *GetAppealReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_appeal_v1_appeal_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppealReply.ProtoReflect.Descriptor instead.
func (*GetAppealReply) Descriptor() ([]byte, []int) {
	return file_api_appeal_v1_appeal_proto_rawDescGZIP(), []int{7}
}

type ListAppealRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListAppealRequest) Reset() {
	*x = ListAppealRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_appeal_v1_appeal_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAppealRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAppealRequest) ProtoMessage() {}

func (x *ListAppealRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_appeal_v1_appeal_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAppealRequest.ProtoReflect.Descriptor instead.
func (*ListAppealRequest) Descriptor() ([]byte, []int) {
	return file_api_appeal_v1_appeal_proto_rawDescGZIP(), []int{8}
}

type ListAppealReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListAppealReply) Reset() {
	*x = ListAppealReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_appeal_v1_appeal_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAppealReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAppealReply) ProtoMessage() {}

func (x *ListAppealReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_appeal_v1_appeal_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAppealReply.ProtoReflect.Descriptor instead.
func (*ListAppealReply) Descriptor() ([]byte, []int) {
	return file_api_appeal_v1_appeal_proto_rawDescGZIP(), []int{9}
}

var File_api_appeal_v1_appeal_proto protoreflect.FileDescriptor

var file_api_appeal_v1_appeal_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x70, 0x70, 0x65, 0x61, 0x6c, 0x2f, 0x76, 0x31, 0x2f,
	0x61, 0x70, 0x70, 0x65, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x61, 0x70,
	0x69, 0x2e, 0x61, 0x70, 0x70, 0x65, 0x61, 0x6c, 0x2e, 0x76, 0x31, 0x1a, 0x17, 0x76, 0x61, 0x6c,
	0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x85, 0x01, 0x0a, 0x15, 0x4f, 0x70, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x41, 0x70, 0x70, 0x65, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24,
	0x0a, 0x09, 0x61, 0x70, 0x70, 0x65, 0x61, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x22, 0x02, 0x20, 0x00, 0x52, 0x08, 0x61, 0x70, 0x70, 0x65,
	0x61, 0x6c, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x09, 0x6f, 0x70, 0x5f, 0x72, 0x65, 0x6d, 0x61, 0x72,
	0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x10, 0x02,
	0x52, 0x08, 0x6f, 0x70, 0x52, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x12, 0x20, 0x0a, 0x07, 0x6f, 0x70,
	0x5f, 0x75, 0x73, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04,
	0x72, 0x02, 0x10, 0x02, 0x52, 0x06, 0x6f, 0x70, 0x55, 0x73, 0x65, 0x72, 0x22, 0x15, 0x0a, 0x13,
	0x4f, 0x70, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x70, 0x70, 0x65, 0x61, 0x6c, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x15, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x70, 0x70,
	0x65, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x13, 0x0a, 0x11, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x41, 0x70, 0x70, 0x65, 0x61, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x15, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x70, 0x70, 0x65, 0x61, 0x6c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x13, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x41, 0x70, 0x70, 0x65, 0x61, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x12, 0x0a, 0x10, 0x47,
	0x65, 0x74, 0x41, 0x70, 0x70, 0x65, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x10, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x41, 0x70, 0x70, 0x65, 0x61, 0x6c, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x13, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x70, 0x70, 0x65, 0x61, 0x6c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x11, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x70,
	0x70, 0x65, 0x61, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x32, 0xad, 0x03, 0x0a, 0x06, 0x41, 0x70,
	0x70, 0x65, 0x61, 0x6c, 0x12, 0x5a, 0x0a, 0x0e, 0x4f, 0x70, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x41, 0x70, 0x70, 0x65, 0x61, 0x6c, 0x12, 0x24, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x70, 0x70,
	0x65, 0x61, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x70, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41,
	0x70, 0x70, 0x65, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x61, 0x70, 0x70, 0x65, 0x61, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x70, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x70, 0x70, 0x65, 0x61, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x54, 0x0a, 0x0c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x70, 0x70, 0x65, 0x61, 0x6c,
	0x12, 0x22, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x70, 0x70, 0x65, 0x61, 0x6c, 0x2e, 0x76, 0x31,
	0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x70, 0x70, 0x65, 0x61, 0x6c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x70, 0x70, 0x65, 0x61,
	0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x70, 0x70, 0x65, 0x61,
	0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x54, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x41, 0x70, 0x70, 0x65, 0x61, 0x6c, 0x12, 0x22, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x70, 0x70,
	0x65, 0x61, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x70, 0x70,
	0x65, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x61, 0x70, 0x70, 0x65, 0x61, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x41, 0x70, 0x70, 0x65, 0x61, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x4b, 0x0a, 0x09,
	0x47, 0x65, 0x74, 0x41, 0x70, 0x70, 0x65, 0x61, 0x6c, 0x12, 0x1f, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x61, 0x70, 0x70, 0x65, 0x61, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x70, 0x70,
	0x65, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x61, 0x70, 0x70, 0x65, 0x61, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x70,
	0x70, 0x65, 0x61, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x4e, 0x0a, 0x0a, 0x4c, 0x69, 0x73,
	0x74, 0x41, 0x70, 0x70, 0x65, 0x61, 0x6c, 0x12, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x70,
	0x70, 0x65, 0x61, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x70, 0x70, 0x65,
	0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x61, 0x70, 0x70, 0x65, 0x61, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x70,
	0x70, 0x65, 0x61, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x2e, 0x0a, 0x0e, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x61, 0x70, 0x70, 0x65, 0x61, 0x6c, 0x2e, 0x76, 0x31, 0x50, 0x01, 0x5a, 0x1a, 0x72,
	0x65, 0x76, 0x69, 0x65, 0x77, 0x2d, 0x6f, 0x2f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x70, 0x70,
	0x65, 0x61, 0x6c, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_api_appeal_v1_appeal_proto_rawDescOnce sync.Once
	file_api_appeal_v1_appeal_proto_rawDescData = file_api_appeal_v1_appeal_proto_rawDesc
)

func file_api_appeal_v1_appeal_proto_rawDescGZIP() []byte {
	file_api_appeal_v1_appeal_proto_rawDescOnce.Do(func() {
		file_api_appeal_v1_appeal_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_appeal_v1_appeal_proto_rawDescData)
	})
	return file_api_appeal_v1_appeal_proto_rawDescData
}

var file_api_appeal_v1_appeal_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_appeal_v1_appeal_proto_goTypes = []any{
	(*OpCreateAppealRequest)(nil), // 0: api.appeal.v1.OpCreateAppealRequest
	(*OpCreateAppealReply)(nil),   // 1: api.appeal.v1.OpCreateAppealReply
	(*UpdateAppealRequest)(nil),   // 2: api.appeal.v1.UpdateAppealRequest
	(*UpdateAppealReply)(nil),     // 3: api.appeal.v1.UpdateAppealReply
	(*DeleteAppealRequest)(nil),   // 4: api.appeal.v1.DeleteAppealRequest
	(*DeleteAppealReply)(nil),     // 5: api.appeal.v1.DeleteAppealReply
	(*GetAppealRequest)(nil),      // 6: api.appeal.v1.GetAppealRequest
	(*GetAppealReply)(nil),        // 7: api.appeal.v1.GetAppealReply
	(*ListAppealRequest)(nil),     // 8: api.appeal.v1.ListAppealRequest
	(*ListAppealReply)(nil),       // 9: api.appeal.v1.ListAppealReply
}
var file_api_appeal_v1_appeal_proto_depIdxs = []int32{
	0, // 0: api.appeal.v1.Appeal.OpCreateAppeal:input_type -> api.appeal.v1.OpCreateAppealRequest
	2, // 1: api.appeal.v1.Appeal.UpdateAppeal:input_type -> api.appeal.v1.UpdateAppealRequest
	4, // 2: api.appeal.v1.Appeal.DeleteAppeal:input_type -> api.appeal.v1.DeleteAppealRequest
	6, // 3: api.appeal.v1.Appeal.GetAppeal:input_type -> api.appeal.v1.GetAppealRequest
	8, // 4: api.appeal.v1.Appeal.ListAppeal:input_type -> api.appeal.v1.ListAppealRequest
	1, // 5: api.appeal.v1.Appeal.OpCreateAppeal:output_type -> api.appeal.v1.OpCreateAppealReply
	3, // 6: api.appeal.v1.Appeal.UpdateAppeal:output_type -> api.appeal.v1.UpdateAppealReply
	5, // 7: api.appeal.v1.Appeal.DeleteAppeal:output_type -> api.appeal.v1.DeleteAppealReply
	7, // 8: api.appeal.v1.Appeal.GetAppeal:output_type -> api.appeal.v1.GetAppealReply
	9, // 9: api.appeal.v1.Appeal.ListAppeal:output_type -> api.appeal.v1.ListAppealReply
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_appeal_v1_appeal_proto_init() }
func file_api_appeal_v1_appeal_proto_init() {
	if File_api_appeal_v1_appeal_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_appeal_v1_appeal_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*OpCreateAppealRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_appeal_v1_appeal_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*OpCreateAppealReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_appeal_v1_appeal_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateAppealRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_appeal_v1_appeal_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateAppealReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_appeal_v1_appeal_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteAppealRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_appeal_v1_appeal_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteAppealReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_appeal_v1_appeal_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*GetAppealRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_appeal_v1_appeal_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*GetAppealReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_appeal_v1_appeal_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*ListAppealRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_appeal_v1_appeal_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*ListAppealReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_appeal_v1_appeal_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_appeal_v1_appeal_proto_goTypes,
		DependencyIndexes: file_api_appeal_v1_appeal_proto_depIdxs,
		MessageInfos:      file_api_appeal_v1_appeal_proto_msgTypes,
	}.Build()
	File_api_appeal_v1_appeal_proto = out.File
	file_api_appeal_v1_appeal_proto_rawDesc = nil
	file_api_appeal_v1_appeal_proto_goTypes = nil
	file_api_appeal_v1_appeal_proto_depIdxs = nil
}
